"""create customers and reservations tables

Revision ID: 2886d72156f0
Revises: 
Create Date: 2026-07-22 20:43:25.763350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2886d72156f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('newsletter_signup', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email_address'), ['email_address'], unique=True)

    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.DateTime(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('number_of_guests', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('number_of_guests BETWEEN 1 AND 12', name='ck_reservations_number_of_guests_range'),
    sa.CheckConstraint('table_number BETWEEN 1 AND 30', name='ck_reservations_table_number_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('time_slot', 'table_number', name='uq_reservations_time_slot_table_number')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_time_slot'), ['time_slot'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_time_slot'))
        batch_op.drop_index(batch_op.f('ix_reservations_customer_id'))

    op.drop_table('reservations')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_email_address'))

    op.drop_table('customers')
    # ### end Alembic commands ###
